import { describe, expect, test } from "bun:test";
import {
	createTag,
	createTags,
} from "../../src/admin/routes/tags/tag-service.js";

const buildDatabase = (initialTags: object[] = []) => {
	const tags = [...initialTags] as Array<{
		id: number;
		title: string;
		color: string;
		reviewed: boolean;
	}>;
	let nextId = tags.length + 1;

	return {
		database: {
			selectFrom: () => ({
				select: () => ({ execute: async () => tags }),
			}),
			insertInto: () => {
				let values: {
					title: string;
					color: string;
					reviewed: boolean;
				};
				const builder = {
					values: (input: typeof values) => {
						values = input;
						return builder;
					},
					returning: () => builder,
					executeTakeFirstOrThrow: async () => {
						const tag = { id: nextId++, ...values };
						tags.push(tag);
						return tag;
					},
				};
				return builder;
			},
		} as never,
		tags,
	};
};

describe("tag service", () => {
	test("creates an autogenerated-color tag as unreviewed", async () => {
		const { database } = buildDatabase();

		const tag = await createTag(database, { title: " Dance " });

		expect(tag.title).toBe("Dance");
		expect(tag.reviewed).toBe(false);
		expect(tag.color).toMatch(/^#[0-9a-f]{6}$/);
	});

	test("creates an explicitly colored tag as reviewed", async () => {
		const { database } = buildDatabase();

		const tag = await createTag(database, {
			title: "Dance",
			color: "#123456",
		});

		expect(tag).toEqual({
			id: 1,
			title: "Dance",
			color: "#123456",
			reviewed: true,
		});
	});

	test("reuses existing tags and deduplicates a batch", async () => {
		const { database } = buildDatabase([
			{ id: 7, title: "Dance", color: "#123456", reviewed: true },
		]);

		const tags = await createTags(database, [
			{ title: " dance " },
			{ title: "DANCE" },
			{ title: "House" },
		]);

		expect(tags.map((tag) => tag.id)).toEqual([7, 2]);
		expect(tags[0]?.reviewed).toBe(true);
	});
});
