import { afterEach, describe, expect, spyOn, test } from "bun:test";
import {
	createTag,
	createTags,
} from "../../src/admin/routes/tags/tag-service.js";

const buildDatabase = (initialTags: object[] = []) => {
	const tags = [...initialTags] as Array<{
		id: number;
		title: string;
		color: string;
		reviewed: boolean;
		mixcloud_key: string | null;
		mixcloud_url: string | null;
	}>;
	let nextId = tags.length + 1;

	return {
		database: {
			selectFrom: () => ({
				select: () => ({ execute: async () => tags }),
			}),
			insertInto: () => {
				let values: {
					title: string;
					color: string;
					reviewed: boolean;
					mixcloud_key: string | null;
					mixcloud_url: string | null;
				};
				const builder = {
					values: (input: typeof values) => {
						values = input;
						return builder;
					},
					returning: () => builder,
					executeTakeFirstOrThrow: async () => {
						const tag = { id: nextId++, ...values };
						tags.push(tag);
						return tag;
					},
				};
				return builder;
			},
		} as never,
		tags,
	};
};

const originalRandom = Math.random;
afterEach(() => {
	Math.random = originalRandom;
});

// Independent RGB measurements verify the persisted, rounded color.
const measureColor = (color: string) => {
	const rgb = [1, 3, 5].map(
		(index) => Number.parseInt(color.slice(index, index + 2), 16) / 255,
	);
	const maximum = Math.max(...rgb);
	const minimum = Math.min(...rgb);
	const lightness = (maximum + minimum) / 2;
	const saturation = (maximum - minimum) / (1 - Math.abs(2 * lightness - 1));
	return { saturation, lightness };
};

describe("tag service", () => {
	test("automatic colors cover hue sectors and approved color boundaries", async () => {
		const random = spyOn(Math, "random");
		for (let hue = 0; hue <= 360; hue += 15) {
			for (const saturation of [0, 1 - Number.EPSILON]) {
				for (const lightness of [0, 1 - Number.EPSILON]) {
					random.mockReset();
					random
						.mockReturnValueOnce(Math.min(hue / 360, 1 - Number.EPSILON))
						.mockReturnValueOnce(saturation)
						.mockReturnValueOnce(lightness);
					const { database } = buildDatabase();
					const tag = await createTag(database, { title: "Generated" });
					expect(tag.color).toMatch(/^#[0-9a-f]{6}$/);
					expect(tag.reviewed).toBe(false);
					const measured = measureColor(tag.color);
					// RGB rounding permits 1 percentage point of saturation error.
					expect(measured.saturation).toBeGreaterThanOrEqual(0.83);
					expect(measured.saturation).toBeLessThanOrEqual(0.97);
					expect(
						Math.abs(measured.saturation - (0.84 + saturation * 0.12)),
					).toBeLessThanOrEqual(0.01);
					expect(measured.lightness).toBeCloseTo(0.62 + lightness * 0.15, 2);
				}
			}
		}
	});

	test("deterministic hue sectors produce distinct expected colors", async () => {
		const random = spyOn(Math, "random");
		const colors: string[] = [];
		for (let sector = 0; sector < 6; sector++) {
			random.mockReset();
			random
				.mockReturnValueOnce(sector / 6)
				.mockReturnValueOnce(0)
				.mockReturnValueOnce(0);
			colors.push(
				(await createTag(buildDatabase().database, { title: "Generated" }))
					.color,
			);
		}
		expect(colors).toEqual([
			"#ef4d4d",
			"#efef4d",
			"#4def4d",
			"#4defef",
			"#4d4def",
			"#ef4def",
		]);
	});

	test("creates an autogenerated-color tag as unreviewed", async () => {
		const { database } = buildDatabase();

		const tag = await createTag(database, { title: " Dance " });

		expect(tag.title).toBe("Dance");
		expect(tag.reviewed).toBe(false);
		expect(tag.color).toMatch(/^#[0-9a-f]{6}$/);
	});

	test("batch creation leaves every automatic tag unreviewed", async () => {
		const tags = await createTags(buildDatabase().database, [
			{ title: "House" },
			{ title: "Ambient" },
			{ title: " house " },
		]);
		expect(tags).toHaveLength(2);
		for (const tag of tags) {
			expect(tag.reviewed).toBe(false);
		}
	});

	test("reuse preserves an unreviewed tag even when supplied an explicit color", async () => {
		const { database, tags } = buildDatabase([
			{
				id: 1,
				title: "Ambient",
				color: "#010203",
				reviewed: false,
				mixcloud_key: null,
				mixcloud_url: null,
			},
		]);
		const tag = await createTag(database, {
			title: " AMBIENT ",
			color: "#ffffff",
		});
		expect(tag).toMatchObject({ id: 1, color: "#010203", reviewed: false });
		expect(tags).toHaveLength(1);
	});

	test("persists optional Mixcloud metadata", async () => {
		const { database } = buildDatabase();

		const tag = await createTag(database, {
			title: "Experimental",
			mixcloud_key: " /genres/experimental/ ",
			mixcloud_url: " https://www.mixcloud.com/genres/experimental/ ",
		});

		expect(tag).toMatchObject({
			title: "Experimental",
			mixcloud_key: "/genres/experimental/",
			mixcloud_url: "https://www.mixcloud.com/genres/experimental/",
		});
	});

	test("creates an explicitly colored tag as reviewed", async () => {
		const { database } = buildDatabase();

		const tag = await createTag(database, {
			title: "Dance",
			color: "#123456",
		});

		expect(tag).toEqual({
			id: 1,
			title: "Dance",
			color: "#123456",
			reviewed: true,
		});
	});

	test("reuses existing tags and deduplicates a batch", async () => {
		const { database } = buildDatabase([
			{
				id: 7,
				title: "Dance",
				color: "#123456",
				reviewed: true,
				mixcloud_key: null,
				mixcloud_url: null,
			},
		]);

		const tags = await createTags(database, [
			{ title: " dance " },
			{ title: "DANCE" },
			{ title: "House" },
		]);

		expect(tags.map((tag) => tag.id)).toEqual([7, 2]);
		expect(tags[0]).toMatchObject({ color: "#123456", reviewed: true });
		expect(tags[1]?.reviewed).toBe(false);
		expect(tags[1]?.color).toMatch(/^#[0-9a-f]{6}$/);
	});
});
