#!/usr/bin/env bash
set -uo pipefail

compose=(docker compose --project-name archive-backend-integration -f compose.integration.yml)
cleanup() {
	"${compose[@]}" down --volumes --remove-orphans
}
trap cleanup EXIT

"${compose[@]}" up --build --wait api
"${compose[@]}" run --rm --build test
exit $?
