#!/usr/bin/env bash
set -uo pipefail

compose=(docker compose --project-name archive-backend-integration -f compose.integration.yml)
cleanup() {
	"${compose[@]}" down --volumes --remove-orphans
}
trap cleanup EXIT

"${compose[@]}" up --build --abort-on-container-exit --exit-code-from test
exit $?
